spring.application.name=ticketlive

spring.datasource.url=jdbc:mysql://localhost:3306/db_ticketlive
spring.datasource.username=root
spring.datasource.password=Chlp39100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=AgyQiMJSRFm9QIMFkzy7t7UiijHx6qQlNxNZ61X/2qAgUVJ/M1ojBJPsNNmzvVVDTyc=
app.jwt.expiration-ms=86400000

stripe.secret-key=sk_test_51UFsvhFzCYL353ym4P65guJ2LkiAQWm4Dqb3FsWcmWZ3byoUXqefrmHwAmQtPXITJ5U1y9eAlaXzJQ9WJcJOpSfe00QyrcPsQh
stripe.webhook.secret=whsec_your_webhook_secret